stages:
  - lint

eslint:
  stage: lint
  variables:
    NODE_VERSION: 16.5.0
  script:
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
    - nvm install
    - npm i
    - npm run lint
