stages:
  - lint
  - build
  - push
  - deploy
  - review

.node:
  image: node:16-alpine

  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/

  before_script:
    - npm ci --cache .npm --prefer-offline --no-audit

.docker:
  image: docker:20
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

.registry-auth:
  before_script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY

lint:
  stage: lint
  extends:
    - .node
  script:
    - npm run lint
    - npm run check:format
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

build:
  stage: build
  extends:
    - .docker
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - >
      docker build
      --pull
      --cache-from $CI_REGISTRY_IMAGE:latest
      -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
      -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
      .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

push_latest:
  stage: push
  extends:
    - .docker
  variables:
    GIT_STRATEGY: none
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - main

deploy:
  stage: deploy
  tags:
    - remote
  extends:
    - .registry-auth
  variables:
    GIT_STRATEGY: none
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - mkdir -p ~/deploy/$CI_COMMIT_REF_SLUG
    - cp ~/docker-compose.yml ~/deploy/$CI_COMMIT_REF_SLUG/
    - docker stack deploy $CI_COMMIT_REF_SLUG -c ~/deploy/$CI_COMMIT_REF_SLUG/docker-compose.yml --with-registry-auth
  environment:
    name: production
    url: http://$CI_COMMIT_REF_SLUG.$APP_HOST
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

create_review_app:
  stage: review
  tags:
    - remote
  extends:
    - .registry-auth
  variables:
    GIT_STRATEGY: none
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - mkdir -p ~/deploy/$CI_COMMIT_REF_SLUG
    - cp ~/docker-compose.yml ~/deploy/$CI_COMMIT_REF_SLUG/
    - docker stack deploy $CI_COMMIT_REF_SLUG -c ~/deploy/$CI_COMMIT_REF_SLUG/docker-compose.yml --with-registry-auth
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://$CI_COMMIT_REF_SLUG.$APP_HOST/
    on_stop: remove_review_app
  rules:
    - if: '$CI_MERGE_REQUEST_TITLE =~ /\[SKIP REVIEW\]/'
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

create_review_app_frontend:
  needs:
    - create_review_app
  trigger:
    project: 'chenaski/react-redux-realworld-example-app'
    strategy: depend
  variables:
    REMOTE_REF: $CI_COMMIT_REF_NAME
  rules:
    - if: '$CI_MERGE_REQUEST_TITLE =~ /\[SKIP REVIEW\]/'
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

remove_review_app:
  stage: review
  tags:
    - remote
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  variables:
    GIT_STRATEGY: none
  script:
    - docker stack rm $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker rmi $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - rm -rf ~/deploy/$CI_COMMIT_REF_SLUG
  rules:
    - if: '$CI_MERGE_REQUEST_TITLE =~ /\[SKIP REVIEW\]/'
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
