stages:
  - lint

eslint:
  stage: lint
  image: node:16-alpine
  script:
    - npm i
    - npm run lint

prettier:
  stage: lint
  image: node:16-alpine
  script:
    - npm i
    - npm run check:format
