stages:
  - lint
  - deploy

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

.default-cache: &default-cache
  before_script:
    - npm ci --cache .npm --prefer-offline --no-audit

eslint:
  extends:
    - .default-cache
  stage: lint
  image: node:16-alpine
  script:
    - npm run lint

prettier:
  extends:
    - .default-cache
  stage: lint
  image: node:16-alpine
  script:
    - npm run check:format

deploy:
  stage: deploy
  script:
    - apt -qq update && apt -qqy install rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - ssh-keyscan -t ecdsa -H $APP_HOST >> ~/.ssh/known_hosts
    - rsync -a --progress --human-readable --delete
      --exclude-from .gitignore
      --exclude .gitignore
      --exclude .git
      --exclude public
      . deploy@$APP_HOST:~/realworld/
    - ssh deploy@$APP_HOST "pushd ~/realworld && npm i --production && popd && pm2 restart ecosystem.config.js"
