stages:
  - lint

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

eslint:
  stage: lint
  image: node:16-alpine
  script:
    - npm ci
    - npm run lint

prettier:
  stage: lint
  image: node:16-alpine
  script:
    - npm ci
    - npm run check:format
