name: Create review app

on:
  pull_request:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup SSH
        env:
          IP: ${{ secrets.IP }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_ecdsa
          chmod 600 ~/.ssh/id_ecdsa
          ssh-keyscan -t ecdsa -H $IP >> ~/.ssh/known_hosts

      - name: Copy files to the server
        env:
          IP: ${{ secrets.IP }}
          BRANCH_NAME: ${{ github.head_ref }}
        run: |
          rsync -a --progress --human-readable --delete \
            --exclude-from .gitignore \
            --exclude .gitignore \
            --exclude .git \
            --exclude public \
            . deploy@$IP:~/app/$BRANCH_NAME/

      - name: Start application
        env:
          IP: ${{ secrets.IP }}
          BRANCH_NAME: ${{ github.head_ref }}
          DB_NAME: ${{ github.head_ref }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          ssh deploy@$IP "DB_NAME=$DB_NAME DB_PASSWORD=$DB_PASSWORD envsubst < ecosystem.config.js > ~/app/$BRANCH_NAME/ecosystem.config.js && pushd ~/app/$BRANCH_NAME && ./bin/create-db-copy.sh $DB_PASSWORD $BRANCH_NAME && npm i --production && pm2 restart ecosystem.config.js --name $BRANCH_NAME --env production && popd"
