name: Create review app

on:
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup SSH
        env:
          APP_HOST: ${{ secrets.APP_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_ecdsa
          chmod 600 ~/.ssh/id_ecdsa
          ssh-keyscan -t ecdsa -H $APP_HOST >> ~/.ssh/known_hosts

      - name: Copy files to the server
        env:
          APP_HOST: ${{ secrets.APP_HOST }}
          BRANCH_NAME: ${{ github.head_ref }}
        run: |
          rsync -a --progress --human-readable --delete \
            --exclude-from .gitignore \
            --exclude .gitignore \
            --exclude .git \
            --exclude public \
            . deploy@$APP_HOST:~/app/$BRANCH_NAME/

      - name: Start application
        env:
          APP_HOST: ${{ secrets.APP_HOST }}
          BRANCH_NAME: ${{ github.head_ref }}
          DB_NAME: ${{ github.head_ref }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          ssh deploy@$APP_HOST "DB_NAME=$DB_NAME DB_PASSWORD=$DB_PASSWORD envsubst < ecosystem.config.js > ~/app/$BRANCH_NAME/ecosystem.config.js && pushd ~/app/$BRANCH_NAME && pm2 stop ecosystem.config.js && ./bin/create-db-copy.sh $BRANCH_NAME && npm i --production && pm2 restart ecosystem.config.js && popd"

  deploy-frontend:
    name: Deploy frontend
    runs-on: ubuntu-latest
    steps:
      - id: check-branch
        continue-on-error: true
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          route: GET /repos/{owner}/{repo}/git/ref/:ref
          owner: chenaski
          repo: react-redux-realworld-example-app
          ref: ${{ github.head_ref }}

      - if: steps.check-branch.output.status == 200
        name: Trigger fronted review app
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          route: POST /repos/{owner}/{repo}/actions/workflows/publish-review-app.yml/dispatches
          owner: chenaski
          repo: react-redux-realworld-example-app
          ref: ${{ github.head_ref }}
          inputs: |
            ref: ${{ github.head_ref }}
            dest: ${{ github.head_ref }}

      - if: steps.check-branch.output.status != 200
        name: Trigger fronted review app
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          route: POST /repos/{owner}/{repo}/actions/workflows/publish-review-app.yml/dispatches
          owner: chenaski
          repo: react-redux-realworld-example-app
          ref: main
          inputs: |
            ref: main
            dest: ${{ github.head_ref }}
