name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_ecdsa
          chmod 600 ~/.ssh/id_ecdsa
          ssh-keyscan -t ecdsa -H $IP >> ~/.ssh/known_hosts

      - name: Copy files to the server
        env:
          IP: ${{ secrets.IP }}
        run: |
          rsync -a --progress --human-readable --delete \
            --exclude-from '.gitignore' \
            --exclude .gitignore \
            --exclude .git \
            --exclude public \
            . deploy@$IP:~/realworld

      - name: Restart application
        env:
          IP: ${{ secrets.IP }}
        run: |
          ssh deploy@$IP "pushd realworld && npm i --production && popd && pm2 restart ecosystem.config.js"
