name: eslint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i

      - name: Lint source code with ESLint
        run: npm run lint

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i

      - name: Lint source code with Prettier
        run: npm run check:format
