name: Reset DB

on:
  workflow_dispatch:

jobs:
  reset-db:
    name: Reset
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSh
        env:
          IP: ${{ secrets.IP }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_ecdsa
          chmod 600 ~/.ssh/id_ecdsa
          ssh-keyscan -t ecdsa -H $IP >> ~/.ssh/known_hosts

      - name: Run reset db script
        env:
          IP: ${{ secrets.IP }}
          BRANCH_NAME: ${{ github.head_ref }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          ssh deploy@$IP "pushd ~/app/$BRANCH_NAME && pm2 stop ecosystem.config.js && ./bin/craete-db-copy.sh $DB_PASSWORD $BRANCH_NAME && pm2 restart ecosystem.config.js && popd"
